# =========================================================================
# MyKeyManager All-in-One Docker Hub Deployment
# Uses pre-built image from Docker Hub for instant deployment
# =========================================================================

version: '3.8'

services:
  mykeymanager-all-in-one:
    image: acwild/mykeymanager-all-in-one:latest
    container_name: mykeymanager-all-in-one
    
    ports:
      - "${MYKEYMANAGER_PORT:-80}:80"
    
    environment:
      # Database Configuration (internal to container)
      - DATABASE_URL=postgresql://mykeymanager_user:${POSTGRES_PASSWORD:-secure_password_here}@localhost:5432/mykeymanager
      
      # Redis Configuration (internal to container)
      - REDIS_URL=redis://localhost:6379/0
      
      # Security Configuration
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-this-in-production}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      
      # SMTP Configuration
      - SMTP_HOST=${SMTP_HOST:-localhost}
      - SMTP_PORT=${SMTP_PORT:-25}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@mykeymanager.local}
      
      # Application Configuration
      - DEBUG=${DEBUG:-false}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost,http://127.0.0.1}
      
      # Timezone
      - TZ=${TZ:-Europe/Rome}
    
    volumes:
      # Persistent data for database
      - postgres_data:/var/lib/postgresql/14/main
      
      # Persistent logs
      - app_logs:/app/logs
      
      # Optional: Custom configuration
      - ./custom-config:/app/config:ro
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["/app/scripts/health.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
    
    # Labels for Docker management
    labels:
      - "com.mykeymanager.service=all-in-one"
      - "com.mykeymanager.version=v1.1.1"
      - "com.mykeymanager.description=Complete license management system"

volumes:
  postgres_data:
    driver: local
    name: mykeymanager_postgres_data
  
  app_logs:
    driver: local
    name: mykeymanager_logs

# =========================================================================
# Networks (optional)
# =========================================================================

networks:
  default:
    name: mykeymanager-network
