# =========================================================================
# MyKeyManager - Docker Compose Ottimizzato per CasaOS
# =========================================================================

name: mykeymanager

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: mykeymanager-db
    hostname: mykeymanager-db
    environment:
      POSTGRES_DB: mykeymanager
      POSTGRES_USER: mykeymanager
      POSTGRES_PASSWORD: SecurePass123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Usa il percorso standard CasaOS per persistenza dati
      - /DATA/AppData/mykeymanager/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mykeymanager-net
    # Ottimizzato per CasaOS (risorse limitate)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mykeymanager -d mykeymanager"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: mykeymanager-redis
    hostname: mykeymanager-redis
    volumes:
      - /DATA/AppData/mykeymanager/redis:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - mykeymanager-net
    # Configurazione Redis ottimizzata per CasaOS
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    image: acwild/mykeymanager-backend:v1.1.3
    container_name: mykeymanager-backend
    hostname: mykeymanager-backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Database connection
      DATABASE_URL: postgresql://mykeymanager:SecurePass123@mykeymanager-db:5432/mykeymanager
      REDIS_URL: redis://mykeymanager-redis:6379
      
      # Security (CAMBIA in produzione!)
      SECRET_KEY: casaos-change-this-secret-key-in-production
      
      # CORS - Aggiorna con l'IP del tuo CasaOS
      ALLOWED_ORIGINS: http://localhost:8080,http://192.168.1.100:8080
      CORS_ORIGINS: '["http://localhost:8080","http://192.168.1.100:8080"]'
      
      # App configuration
      APP_VERSION: v1.1.3
      
      # Ottimizzazioni per CasaOS
      WORKERS: 2
      MAX_CONNECTIONS: 50
      
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - mykeymanager-net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Web Interface
  frontend:
    image: acwild/mykeymanager-frontend:v1.1.2
    container_name: mykeymanager-frontend
    hostname: mykeymanager-frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      # API URL - Aggiorna con l'IP del tuo CasaOS
      VITE_API_URL: http://localhost:8001/api
      VITE_APP_VERSION: v1.1.2
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - mykeymanager-net
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  mykeymanager-net:
    driver: bridge
    name: mykeymanager-network
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

# =========================================================================
# Note per CasaOS:
# 
# 1. Tutti i dati sono salvati in /DATA/AppData/mykeymanager/
# 2. Le risorse sono limitate per sistemi embedded
# 3. Health check configurati per affidabilità
# 4. Rete isolata per sicurezza
# 5. Hostname configurati per risoluzione DNS interna
# 
# Per personalizzare:
# - Cambia le porte se necessario
# - Aggiorna CORS_ORIGINS con l'IP del tuo CasaOS
# - Modifica SECRET_KEY per produzione
# =========================================================================
