# =========================================================================
# MyKeyManager All-in-One Docker Compose
# SIMPLE VERSION - Massima Compatibilità Container Managers
# =========================================================================

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: mykeymanager-db
    environment:
      POSTGRES_DB: mykeymanager
      POSTGRES_USER: mykeymanager
      POSTGRES_PASSWORD: SecurePass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mykeymanager-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: mykeymanager-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - mykeymanager-network

  # Backend API
  backend:
    image: acwild/mykeymanager-backend:v1.1.2
    container_name: mykeymanager-backend
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://mykeymanager:SecurePass123@db:5432/mykeymanager
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-change-in-production
      ALLOWED_ORIGINS: http://localhost:8080
      CORS_ORIGINS: '["http://localhost:8080"]'
      APP_VERSION: v1.1.2
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - mykeymanager-network

  # Frontend Web Interface
  frontend:
    image: acwild/mykeymanager-frontend:v1.1.1
    container_name: mykeymanager-frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8001/api
      VITE_APP_VERSION: v1.1.1
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - mykeymanager-network

volumes:
  postgres_data:
    name: mykeymanager_postgres_data
  redis_data:
    name: mykeymanager_redis_data

networks:
  mykeymanager-network:
    driver: bridge
