# =========================================================================
# MyKeyManager - Docker Compose per CasaOS (Versione No-Redis)
# =========================================================================

name: mykeymanager

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: mykeymanager-db
    hostname: mykeymanager-db
    environment:
      POSTGRES_DB: mykeymanager
      POSTGRES_USER: mykeymanager
      POSTGRES_PASSWORD: SecurePass123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Usa il percorso standard CasaOS per persistenza dati
      - /DATA/AppData/mykeymanager/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mykeymanager-net
    # Ottimizzato per CasaOS (risorse limitate)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mykeymanager -d mykeymanager"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Backend API
  backend:
    image: acwild/mykeymanager-backend:v1.1.3
    container_name: mykeymanager-backend
    hostname: mykeymanager-backend
    environment:
      # Database
      DATABASE_URL: postgresql://mykeymanager:SecurePass123@db:5432/mykeymanager
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mykeymanager
      POSTGRES_USER: mykeymanager
      POSTGRES_PASSWORD: SecurePass123
      
      # Redis - Disabilitato temporaneamente
      # REDIS_URL: redis://redis:6379/0
      
      # Security
      SECRET_KEY: CasaOS-MyKeyManager-Secret-2024
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 480
      
      # Rate Limiting (memoria invece di Redis)
      RATE_LIMIT: "100/hour"
      
      # CORS
      ALLOWED_ORIGINS: "http://localhost:8080,http://localhost:80"
      
      # SMTP (opzionale)
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_FROM: noreply@casaos.local
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - mykeymanager-net
    depends_on:
      db:
        condition: service_healthy
    # Ottimizzato per CasaOS
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  # Frontend
  frontend:
    image: acwild/mykeymanager-frontend:v1.1.2
    container_name: mykeymanager-frontend
    hostname: mykeymanager-frontend
    environment:
      VITE_API_URL: http://localhost:8001
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - mykeymanager-net
    depends_on:
      backend:
        condition: service_healthy
    # Ottimizzato per CasaOS
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mykeymanager-net:
    driver: bridge
    name: mykeymanager-network

# Volumi gestiti da CasaOS in /DATA/AppData/
# I volumi persistenti sono configurati sui path host
