version: '3.8'

services:
  # ==========================================
  # 🌐 FRONTEND - React + Nginx
  # ==========================================
  frontend:
    image: acwild/mykeymanager-frontend:v1.1.0
    container_name: mykeymanager-frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - mknet
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT:-8000}

  # ==========================================
  # 🚀 BACKEND - FastAPI + Python
  # ==========================================
  backend:
    image: acwild/mykeymanager-backend:v1.1.0
    container_name: mykeymanager-backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      - db
      - redis
    networks:
      - mknet
    restart: unless-stopped
    environment:
      # Database
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB:-mykeymanager}
      POSTGRES_USER: ${POSTGRES_USER:-mykeyuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mykeypass}
      DATABASE_URL: postgresql://${POSTGRES_USER:-mykeyuser}:${POSTGRES_PASSWORD:-mykeypass}@db:5432/${POSTGRES_DB:-mykeymanager}
      
      # Security
      SECRET_KEY: ${SECRET_KEY:-change-this-super-secret-key-in-production-min-32-chars}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      
      # CORS
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:5173,http://localhost,http://127.0.0.1:5173,http://127.0.0.1}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      
      # Redis
      REDIS_URL: redis://redis:6379/0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # Email (optional)
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USE_TLS: ${SMTP_USE_TLS:-true}
      SMTP_USERNAME: ${SMTP_USERNAME:-your-email@gmail.com}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-your-app-password}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@yourdomain.com}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-MyKeyManager}
      
      # Application
      DEBUG: ${DEBUG:-false}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}

  # ==========================================
  # 🗄️ DATABASE - PostgreSQL
  # ==========================================
  db:
    image: postgres:16-alpine
    container_name: mykeymanager-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mykeymanager}
      POSTGRES_USER: ${POSTGRES_USER:-mykeyuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mykeypass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mknet
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"  # Configurable PostgreSQL port

  # ==========================================
  # 🔄 CACHE - Redis
  # ==========================================
  redis:
    image: redis:7-alpine
    container_name: mykeymanager-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - mknet
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"  # Configurable Redis port

  # ==========================================
  # 📧 SMTP Server (Optional)
  # ==========================================
  smtp:
    image: bytemark/smtp
    container_name: mykeymanager-smtp
    networks:
      - mknet
    restart: unless-stopped
    environment:
      RELAY_HOST: ${SMTP_HOST:-smtp.gmail.com}
      RELAY_PORT: ${SMTP_PORT:-587}
      RELAY_USERNAME: ${SMTP_USERNAME:-}
      RELAY_PASSWORD: ${SMTP_PASSWORD:-}

# ==========================================
# 🌐 NETWORKS
# ==========================================
networks:
  mknet:
    driver: bridge

# ==========================================
# 💾 VOLUMES
# ==========================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
